### PR TITLE
Feature/circle ci 2.0

### PR DESCRIPTION
**Pull request by strindhaug**
This is somewhat work in progress still, since some project might require further changes to work, but it seems pretty feature complete now.

Latest tag is `ci2-v0.2.3` 

Documentation and example files is not yet updated.

Since the new circle ci format often requires this script to be loaded multiple times in the .circleci/config.yml file; i recommend adding a CI_SCRIPTS_TAG variable for the tag/branch name, and use this rather than hardcoding the tag everywhere you pull the ci-scripts like this:

```yml
defaults: &defaults
  environment:
    CI_SCRIPTS_TAG: ci2-v0.2.3 # release tag
    # CI_SCRIPTS_TAG: feature/circle-ci-2.0 # commented out development branch
#...
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
#...
      - run:
          name: Install common ci-scripts
          command: git clone -b "${CI_SCRIPTS_TAG}" --single-branch --depth 1 https://github.com/zeppelin-no/ci-scripts.git
#...
```
Note that since variable interpolation does no longer work in the `environment` section of the config, the
initialization of this variable `DOCKER_SHA_TAG` has now been moved into this script so that this line `DOCKER_SHA_TAG: $(echo $CIRCLE_SHA1 | cut -c -7)` does not need to be translated into the new config.

### CODE REVIEW

**Comment by strindhaug** [comment]
I don't get it! Apart from the test build build here which seems to fail because the secrets for this app is apparently set up wrong or the https://motione-prod-tectonic-api.zeppelincloud.com:443 server is wrong or something. 
But when using this branch to build an upgraded zepweb2015 everything seems to work now, even automatic deletion of pods except it doesn't actually update anything.

Unless there is some feature of circle ci i don't know about where it silently just pretends to update when running from a non-master branch. I dont get why it's not doing anything.

**Comment by strindhaug** [comment]
Created custom docker image to further speed up the build:
https://hub.docker.com/r/strindhaug/zep-k8s-build/

It's no really fast.
I think the only reason the test build of this app fails is because the user on motione-prod-tectonic-api.zeppelincloud.com is not admin or something.

**Comment by strindhaug** [comment]
I noticed that https://motione-prod-tectonic-api.zeppelincloud.com:443 was configured with the same password as zepweb2015 uses for https://api.sites.zeppelincloud.com which seemed unlikely to me. So by changing the K8S_ENDPOINT to use the latter the build now succeds.
The K8S_ENDPOINT_DEV as it is currently configured is not able to query the server either but at least the tests as it's written now still succeeds.

**Review by andemork — APPROVED** [review]
LGTM

**Pull request merged**
